{{- if and .Values.persistence.tv.enabled (not .Values.persistence.tv.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "medusa.fullname" . }}-tv
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.tv.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.tv.size | quote }}
  {{- if .Values.persistence.tv.storageClass }}
  {{- if (eq "-" .Values.persistence.tv.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.tv.storageClass }}"
  {{- end }}
  {{- end }}
{{- end -}}