{{- if and .Values.persistence.comics.enabled (not .Values.persistence.comics.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mylar.fullname" . }}-comics
  labels:
    {{- include "mylar.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.comics.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.comics.size | quote }}
  {{- if .Values.persistence.comics.storageClass }}
  {{- if (eq "-" .Values.persistence.comics.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.comics.storageClass }}"
  {{- end }}
  {{- end }}
{{- end -}}